apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
    - name: zookeeper
      image: bitnami/zookeeper:3.8
      env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
      ports: [{ containerPort: 2181 }]
    - name: kafka
      image: bitnami/kafka:3.6
      env:
        - name: KAFKA_ENABLE_KRAFT
          value: "no"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: localhost:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
      ports: [{ containerPort: 9092 }]
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092

