apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-wallet
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: wallet-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-trading
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: trading-engine
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-market-data
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: market-data-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-api-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway

