apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'wallet-service'
        static_configs:
          - targets: ['wallet-service:8080']
      - job_name: 'compliance-service'
        static_configs:
          - targets: ['compliance-service:8080']
      - job_name: 'risk-service'
        static_configs:
          - targets: ['risk-service:8080']
      - job_name: 'treasury-service'
        static_configs:
          - targets: ['treasury-service:8080']
      - job_name: 'market-data-service'
        static_configs:
          - targets: ['market-data-service:8080']
      - job_name: 'trading-engine'
        static_configs:
          - targets: ['trading-engine:8080']
      - job_name: 'identity-service'
        static_configs:
          - targets: ['identity-service:4000']
      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:8090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args: ["--config.file=/etc/prometheus/prometheus.yml"]
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090

