apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-restore-sample
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: restore
          image: mongo:6
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -euo pipefail
              LATEST=$(ls -1 /backup | sort | tail -n1)
              echo "Restoring $LATEST" && mongorestore --uri "$MONGODB_URI" --archive=/backup/$LATEST --drop
          env:
            - name: MONGODB_URI
              value: mongodb://admin:password@mongodb:27017/notification?authSource=admin
          volumeMounts:
            - name: backup
              mountPath: /backup
      volumes:
        - name: backup
          emptyDir: {}

