/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health check */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example ok */
              status?: string;
            };
          };
        };
      };
    };
  };
  "/deposit": {
    /** Deposit funds */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["DepositRequest"];
        };
      };
      responses: {
        /** @description Accepted */
        200: {
          content: {
            "application/json": components["schemas"]["Acknowledgement"];
          };
        };
      };
    };
  };
  "/withdraw": {
    /** Withdraw funds */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["WithdrawRequest"];
        };
      };
      responses: {
        /** @description Accepted */
        200: {
          content: {
            "application/json": components["schemas"]["Acknowledgement"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    DepositRequest: {
      /** @example user_123 */
      userId: string;
      /** @example USDT */
      asset: string;
      /**
       * Format: double
       * @example 100.5
       */
      amount: number;
      /** @example bank-tx-001 */
      reference?: string | null;
    };
    WithdrawRequest: {
      /** @example user_123 */
      userId: string;
      /** @example BTC */
      asset: string;
      /**
       * Format: double
       * @example 0.01
       */
      amount: number;
      /** @example bc1qexampleaddress */
      address: string;
      /** @example Bitcoin */
      network?: string | null;
    };
    Acknowledgement: {
      /** @example accepted */
      status?: string;
      /** @example req_abc123 */
      requestId?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
