apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minhnguyenkhac1983/exc
    targetRevision: main
    path: infrastructure/kubernetes/helm/exc
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


