openapi: 3.0.3
info:
  title: Wallet API
  version: 0.1.0
servers:
  - url: http://localhost:8088/api/wallet
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /deposit:
    post:
      summary: Deposit funds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Acknowledgement'
  /withdraw:
    post:
      summary: Withdraw funds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Acknowledgement'

components:
  schemas:
    DepositRequest:
      type: object
      required: [userId, asset, amount]
      properties:
        userId:
          type: string
          example: user_123
        asset:
          type: string
          example: USDT
        amount:
          type: number
          format: double
          example: 100.5
        reference:
          type: string
          nullable: true
          example: bank-tx-001
    WithdrawRequest:
      type: object
      required: [userId, asset, amount, address]
      properties:
        userId:
          type: string
          example: user_123
        asset:
          type: string
          example: BTC
        amount:
          type: number
          format: double
          example: 0.01
        address:
          type: string
          example: bc1qexampleaddress
        network:
          type: string
          nullable: true
          example: Bitcoin
    Acknowledgement:
      type: object
      properties:
        status:
          type: string
          example: accepted
        requestId:
          type: string
          example: req_abc123


