name: flutter_desktop_trading
description: Flutter Desktop Trading Application for Crypto Exchange
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  
  # HTTP & WebSocket
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Charts & Trading
  fl_chart: ^0.66.0
  candlesticks: ^2.1.0
  syncfusion_flutter_charts: ^24.1.41
  
  # State Management
  riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  
  # Desktop Features
  window_manager: ^0.3.7
  screen_retriever: ^0.1.9
  multi_window: ^0.2.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite_common_ffi: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # File Operations
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  csv: ^5.0.2
  
  # Utils
  decimal: ^2.3.3
  intl: ^0.19.0
  logger: ^2.0.2+1
  uuid: ^4.2.1
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Security
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # System Integration
  system_tray: ^2.0.3
  launch_at_startup: ^0.2.2
  hotkey_manager: ^0.1.8
  
  # UI Enhancement
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Responsive Design
  responsive_framework: ^1.1.1
  
  # Desktop UI
  fluent_ui: ^4.8.4
  macos_ui: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/sounds/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
